AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/EndOfLine:
  Enabled: False

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  IgnoredMethods: ["subject"]

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
